### ISSUE TITLE
Support deleting functions

### ISSUE THREAD

**Issue by davidebbo** [ahmelsayed/AzureFunctions#15]
With confirmation

**Comment by mamoorkhan** [comment]
@ahmelsayed I wanted to deploy Azure Logic App along with the FunctionApp that it is using, via template. It created the FunctionApp but it was in a state of limbo, when I go to the FunctionApp, all the action buttons like `Stop, Swap, Restart, Download publish profile, Reset publish credentials, Download app content` are disabled and I am greeted with the following errors

`Error:
'AzureWebJobsStorage' application setting is missing from your app. This setting contains a connection string for an Azure Storage account that is needed for the functions runtime to handle multiple instances synchronization, log invocation results, and other infrastructure jobs. Your function app will not work correctly without that setting. Create the app setting with a valid storage connection string.
Session Id: 38323265cd3342ebab3ba915c6087947
Timestamp: 2017-06-14T08:25:13.400Z`


`Error:
'WEBSITE_CONTENTAZUREFILECONNECTIONSTRING' application setting is missing from your app. This setting contains a connection string for an Azure Storage account that is used to host your functions content. Your app will be completely broken without this setting. You may need to delete and recreate this function app if you no longer have access to the value of that application setting.
Session Id: 38323265cd3342ebab3ba915c6087947
Timestamp: 2017-06-14T08:25:13.401Z`


`Error:
'WEBSITE_CONTENTSHARE' application setting is missing from your app. This setting contains a share name where your function content lives. Your app will be completely broken without this setting. You may need to delete and recreate this function app if you no longer have access to the value of that application setting.
Session Id: 38323265cd3342ebab3ba915c6087947
Timestamp: 2017-06-14T08:25:13.411Z`
![capture 1](https://user-images.githubusercontent.com/6604239/27122988-52196b6a-50e4-11e7-90e9-ed2e537766b8.PNG)
